# Generated by Django 5.0.6 on 2024-05-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='id',
            field=models.CharField(default='fa5fc6c259f24b6e8bcf089877154bfe', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main',
            name='lineid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.CharField(default='6f9d7dac02524a65a938868f988e20b5', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seven',
            name='id',
            field=models.CharField(default='689c8cf5a08446799803f12d11ace47f', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threemonth',
            name='id',
            field=models.CharField(default='1fb793271210413c92e80f747530a65b', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twomonth',
            name='id',
            field=models.CharField(default='01cd7dee0f5842638d7484e0bf487b8f', max_length=32, primary_key=True, serialize=False),
        ),
    ]
