# Generated by Django 5.0.6 on 2024-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbot', '0002_alter_first_id_alter_main_lineid_alter_month_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='id',
            field=models.CharField(default='caab4271d3da49f4a42ee82c0ea21faa', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.CharField(default='d5d60ac4832b451cbd8d772e129f23ad', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seven',
            name='id',
            field=models.CharField(default='11002bbf9c4b425fb3e4e39ed3d73651', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threemonth',
            name='id',
            field=models.CharField(default='bf33ef2f47434468aa17849c7bfdf561', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twomonth',
            name='id',
            field=models.CharField(default='f93d96b6bcb74d9fa5bda4a7c12f2707', max_length=32, primary_key=True, serialize=False),
        ),
    ]
