# Generated by Django 5.0.6 on 2024-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbot', '0003_alter_first_id_alter_month_id_alter_seven_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='id',
            field=models.CharField(default='ee54f2819c8f4f54b94938bdf2b14013', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.CharField(default='5c7b1197acf940f1b2cb20b445f9af05', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seven',
            name='id',
            field=models.CharField(default='018333e6938b4dd19ddf10a40fafbecf', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threemonth',
            name='id',
            field=models.CharField(default='fc47008e4a9c4747b348b14aa3490b6e', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twomonth',
            name='id',
            field=models.CharField(default='0c8a41501a0a481f857b4d498314a63f', max_length=32, primary_key=True, serialize=False),
        ),
    ]
