# Generated by Django 5.0.6 on 2024-05-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbot', '0005_alter_first_id_alter_main_lineid_alter_month_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='id',
            field=models.CharField(default='64d7a8870ab1452ea15344091d7a0ad5', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='first_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='main',
            name='lineid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='month_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='main',
            name='seven_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='main',
            name='threemonth_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='main',
            name='twomonth_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.CharField(default='5ef4dbb0fe4942449c46ca8680dbf539', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seven',
            name='id',
            field=models.CharField(default='2203997367c042d3b5d155c4c75d4888', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threemonth',
            name='id',
            field=models.CharField(default='1b64acbe260e406aaf8dbea0f907763f', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twomonth',
            name='id',
            field=models.CharField(default='401e768a12c844f8b1e593f586aad88e', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='main',
            unique_together={('lineid', 'days')},
        ),
    ]
