# Generated by Django 5.0.6 on 2024-05-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbot', '0006_alter_first_id_alter_main_days_alter_main_first_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='main',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='first',
            name='id',
            field=models.CharField(default='fbfed3827d9045129560e0c48e5bebb8', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='main',
            name='first_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='month_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='seven_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='threemonth_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='twomonth_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.CharField(default='7cdc0d69af074170b0c3a9eecebe7bed', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seven',
            name='id',
            field=models.CharField(default='a16fe41fe7384decbe5c084ee1f08586', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threemonth',
            name='id',
            field=models.CharField(default='cff4e72dcb0e4ad9903a1b16722a5585', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twomonth',
            name='id',
            field=models.CharField(default='6266883c73304b53904ea323884f6e0b', max_length=32, primary_key=True, serialize=False),
        ),
    ]
